# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190814_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[(b'0', b''), (b'1', b'Usu\xc3\xa1rio'), (b'2', b'Loja')], default=b'0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'nome'),
        ),
    ]
