# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_phone_number1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number1',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'telefone'),
        ),
    ]
