# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190820_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('0', ''), ('1', 'Usuário'), ('2', 'Loja')], default='0', max_length=1),
        ),
    ]
