# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190820_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Homem'), ('2', 'Mulher')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Usuário'), ('2', 'Loja')], max_length=1),
        ),
    ]
