# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190820_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Masculino'), ('2', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Usuário'), ('2', 'Loja')], default=0, max_length=1),
        ),
    ]
