# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unit',
            field=models.CharField(choices=[('pound', 'POUND'), ('gallon', 'GALLON'), ('each', 'EACH')], default='each', max_length=80),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
